CALISAN_PARSEL_SINIR_RENGI = "#0066ff"
CALISAN_PARSEL_SINIR_KALINLIGI = 8

SS_SERIM_RENGI = "#ff1a1a"
SS_SERIM_KALINLIGI = 6
SS_SERIM_KESIK_DESENI = (10, 6)

JEOLOJI_ONAYLI_DOLGU_RENGI = "#ef9a9a"
JEOLOJI_ONAYLI_SINIR_RENGI = "#b71c1c"

JEOLOJI_TASLAK_DOLGU_RENGI = "#ffb74d"
JEOLOJI_TASLAK_SINIR_RENGI = "#ef6c00"

JEOLOJI_SECILI_SINIR_RENGI = "#ffd600"

JEOLOJI_HARITA_RENK_ACIKLAMASI = (
    "Mavi: çalışan parsel · Kırmızı: onaylı rapor · Turuncu: taslak"
)
